version: "3"

services:
  oc_snowtricks_front:
    container_name: oc_snowtricks_front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oc_snowtricks_front.rule=Host(`oc-snowtricks.jojotique.fr`)"
      - "traefik.http.routers.oc_snowtricks_front.entrypoints=websecure"
    restart: always
    networks:
      - traefik
      - postgresql_nt

networks:
  traefik:
    external: true
  postgresql_nt:
    external: true